man/openrc-run.8, sh/supervise-daemon.sh
=> sh/supervise-daemon.sh: use start_stop_daemon_args if supervise_daemon_args is undefined

init.d/modules.in, sh/rc-cgroup.sh.in, sh/s6.sh, sh/start-stop-daemon.sh, src/rc/kill_all.c, src/rc/openrc-init.c, src/rc/rc-wtmp.c, src/rc/supervise-daemon.c
Noticed while running 'make test'.
=> Fix make test (whitespace/style issues)

.cirrus.yml
=> .cirrus.yml: Update FreeBSD releases

sh/rc-cgroup.sh
This should make cgroup_cleanup work successfully since cgroup_get_pids
no longer uses a subshell.
This fixes #396.
=> rc-cgroup.sh: avoid process substitution for cgroup_get_pids

src/rc/seedrng.c
This cleans up the exit path a little bit.
=> seedrng: clean up fds and avoid -1 close on exit

LICENSE
=> LICENSE: Change year to 2023 (from 2015!!!)

src/openrc-run/openrc-run.c, src/start-stop-daemon/start-stop-daemon.c
same rational as 459783bb
Bug: https://github.com/OpenRC/openrc/issues/589
=> avoid malloc inside sig-handler

bash-completion/rc-service
Closes: https://github.com/OpenRC/openrc/issues/344
=> bash-completions/rc-service: don't use grep

etc/rc.conf
it's the high year of 2023, after all.
closes #607
=> rc.conf: default to unicode console

src/shared/helpers.h
Thanks to vapier for noticing.
=> shared: fix pointer type in UNCONST

src/openrc-run/openrc-run.c
svc_exec waits until SIGCHLD comes in to close its input, but in rc_parallel case the SIGCHLD might be unrelated.
Checking the proper pid is found in signal handler and only signaling signal_pipe the status code directly avoids this problem.
This problem only appears when stdout is a tty, e.g. I could reproduce both on start and stop with `while rc-service s1 start && rc-service s2 stop; do date; done`, but not with `while ... done < /dev/null | cat` (s[1-3] from #598)
It'd  just fail with something like this:
```
s3                       |s3 stopped
s1                       |s1 stopped
s2                       | * ERROR: s2 failed to stop
```
reproducing under strace shows s2 tried to write to stdout (from its stop() function) and failed with EIO, because openrc-run already moved on an …
=> openrc-run: fix rc_parallel race in svc_exec

src/librc/librc-daemon.c
Fixes the problem described in https://bugs.gentoo.org/916947 - start-stop-daemon hangs in infinite loop when stopping some daemons on linux 6.6+
It appears linux 6.6 reworked tmpfs, and since then it triggers this problem in openrc:
When iterating over files via `readdir`, running `rename` on a file could result in reading the same file again with next `readdir` call.
The Open Group manual for `readdir` explicitly states "If a file is removed from or added to the directory after the most recent call to [opendir()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/opendir.html) or [rewinddir()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/rewinddir.html), whether a subsequent call to readdir() returns an entry for that file is unspecified.". Linux man page don't …
=> Skip already processed files in rc_service_daemon_set

src/rc-update/rc-update.c
=> change info words "remove" to "delete" in delete sub-command

supervise-daemon-guide.md
Minor formatting adjustments.
No logic/text changes were made.
=> supervise-daemon-guide.md: adjust markdown formatting

etc/rc.conf, init.d/binfmt.in, init.d/cgroups.in, init.d/consolefont.in, init.d/devfs.in, init.d/dmesg.in, init.d/fsck.in, init.d/hostname.in, init.d/hwclock.in, init.d/keymaps.in, init.d/localmount.in, init.d/modules.in, init.d/mount-ro.in, init.d/net-online.in, init.d/netmount.in, init.d/numlock.in, init.d/procfs.in, init.d/root.in, init.d/save-keymaps.in, init.d/save-termencoding.in, init.d/seedrng.in, init.d/swap.in, init.d/swclock.in, init.d/sysfs.in, init.d/termencoding.in, init.d/urandom.in, man/openrc-run.8, sh/rc-functions.sh, src/librc/librc.c, src/librc/rc.h.in
Podman is another container manager akin to Docker, being detectable by checking for the presence of `/.run/containerenv`. Fixes #695.
=> Podman detection

FEATURE-REMOVAL-SCHEDULE.md
these were removed some time ago and there have been no issues, so we can remove the information from this file.
=> FEATURE-REMOVAL-SCHEDULE: remove section on rc and runscript symlinks

src/shared/pipes.c
Ref: https://github.com/OpenRC/openrc/issues/792
=> fix pipe leak, use _exit

man/rc_config.3
Closes: https://github.com/OpenRC/openrc/issues/706
=> man/rc_config.3: fix rc_yesno description

src/openrc-init/openrc-init.c
the current code uses a bunch of signal unsafe functions inside
the signal handlers. this gets those code outside using
self-pipe trick so that there's no more issues.
also save and restore errno inside signal handlers in order to
avoid clobbering errno for the calling code.
the SIGCHLD handler is still seperate since we want to reap
zombies as soon as possible.
Ref: https://github.com/OpenRC/openrc/issues/589
=> openrc-init: use self-pipe to handle signals safely

man/rc-status.8, src/openrc-shutdown/openrc-shutdown.c, src/openrc/rc.c, src/rc-service/rc-service.c, src/rc-status/rc-status.c, src/rc-update/rc-update.c
Some trivial documentation fixes and one memory leak fix.
=> documentation and leak fix

src/shared/pipes.c, src/shared/pipes.h, src/start-stop-daemon/start-stop-daemon.c, src/supervise-daemon/supervise-daemon.c
Closes: https://github.com/OpenRC/openrc/issues/540
=> *-daemon: redirect logger's std{out,err} to devnull

src/openrc-user/openrc-user.c
setting the argv[0] to "-" does not work on alpine which uses busybox as it's shell.
=> openrc-user: support multicall binary shells

sh/openrc-user.sh.in
Fixes: a154efbc0b50075592e2f4152549cfdab976a53d
=> openrc-user: fix typpo

init.d/meson.build, meson.build, meson_options.txt, tools/meson_runlevels.sh
also adds a 'agetty' array option so that user can specify which symlinks he wants to create.
Closes: https://github.com/OpenRC/openrc/pull/355
=> install agetty symlinks via meson

src/shared/misc.c
with this we can define `notify=socket` as an overall systemd "notify-socket" compatibility flag. in the future, `nofiy=socket` will simply enable access to the basic STATUS= command, `socket:ready` enables READY=1, `socket:fdstore` would enable fd-store compat, `socket:watchdog:<timeout>` for the watchdog and so on.
the format of the variable would end up being:
`notify="protocol[:option[,option ...]]"`
=> shared/misc: required `ready` tag for socket notify method

service-script-guide.md
=> service-script-guide: improve markup

src/librc/librc.c
Fixes: https://github.com/OpenRC/openrc/issues/880
=> librc: allow user services to add boot services
