OpenRC/openrc

- init.d/Makefile
- init.d/binfmt.in
- init.d/procfs.in
- runlevels/Makefile
- sh/.gitignore
- sh/Makefile
- sh/binfmt.sh.in
This makes binfmt processing behave like tmpfiles processing which
follows the same specification as systemd.
X-Gentoo-Bug: 545162
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=545162
> Fix binfmt processing

- init.d/modules-load.in
The $RC_UNAME "Linux" had been misspelled as "linux".
As a consequence, entries in e.g. /etc/modules-load.d failed to
load any module succesfully under Linux(!)
> Fix typo in RC_UNAME check of modules-load

- init.d/localmount.in
The /etc/init.d/localmount script has a syntax error that causes it to
attempt to mount remote filesystems, causing the boot to fail. The
script appends a "no" to each remote filesystem type, but it should only
be append the "no" to the beginning of the list.  This patch fixes
localmount on FreeBSD 12.0.  A review of the mount(8) manpage on Ubuntu
12.04 suggests that this patch is correct for Linux, too.
Downstream bug:
https://github.com/trueos/trueos-core/issues/220
> Localmount shouldn't mount remote filesystems

- sh/openrc-run.sh.in
Supervisor setups break easily when start/stop/status functions are not
default.
Applications that write multiple PIDs to a pidfile (eg HAProxy as
described in bug 601540), can also benefit from being able to call the
default start/stop/status with modified environment variables.
Expose the default start/stop/status functions as
openrc_default_start/stop/status, and use them for the defaults
start/stop/status.
Trivial usage example:
```
stop()
{
t=$(mktemp)
for pid in $(cat $pidfile) ; do
echo $pid >$t
pidfile=$t openrc_default_stop
done
rm -f $t
}
```
X-Gentoo-Bug: 601540
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>
> sh/openrc-run.sh: expose default start/stop/status

- sh/init.sh.Linux.in
This will also warn users if md5sum is missing, which serves as a pretty
good indicator that /usr is not mounted.
Supercedes #102
> sh/init.sh.Linux.in: skip /proc test if no md5sum

- init.d/Makefile
Issue appeared for me during building Gentoo/FreeBSD system on Gentoo/Linux host.
It produces following output:
```
install -m 0755 bootmisc fsck hostname local localmount loopback netmount osclock root savecache swap swclock sysctl runsvdir urandom s6-svscan hostid modules mosed newsyslog pf rarpd rc-enabled rpcbind savecore syslogd adjkerntz devd dumpon encswap ipfw modules modules-load mixer nscd powerd syscons /usr/x86_64-gentoo-freebsd10.3/tmp/portage/sys-apps/openrc-0.24.2/image///etc/init.d/
/usr/bin/install: will not overwrite just created '/usr/x86_64-gentoo-freebsd10.3/tmp/portage/sys-apps/openrc-0.24.2/image///etc/init.d/modules' with 'modules'
```
Please note modules being mentioned twice in install parameters. Removing one of appearances fixes issue.
> Fix make install on FreeBSD: don't try to install /etc/init.d/modules twice

- src/rc/rc-logger.c
Truncated crash looked like that:
```
Core was generated by `/sbin/openrc default'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  _IO_new_fclose (fp=0x0) at iofclose.c:53
```
rc_logger_open() has roughly the following code:
```
if ((plog = fopen(logfile, "ae"))) {
if ((log = fopen(TMPLOG, "re"))) {
....
}
fclose(log);
fclose(plog);
}
```
Note that `fclose(log)` is called unconditionally.
The change moves `fclose(log)` up to close file
only it was opened successfully.
Reported-by: Brian Evans <grknight@gentoo.org>
Tested-by: Brian Evans <grknight@gentoo.org>
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
> rc-logger.c: fix crash on fclose(NULL)

- mk/cc.mk
When building openrc from git on uclibg-ng system
a lot of warnings suggest prototypes are missing
for various functions:
```
start-stop-daemon.c:1197:21: warning: implicit declaration of function 'initgroups' [-Wimplicit-function-declaration]
if (changeuser && initgroups(changeuser, gid))
^
start-stop-daemon.c:1197:3: warning: nested extern declaration of 'initgroups' [-Wnested-externs]
if (changeuser && initgroups(changeuser, gid))
^
```
It means all arguments are defaulted to 'int'. It's a
problem for pointer arguments where truncation happens.
To avoid that truncation change forbids inplicit declarations.
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
> mk/cc.mk: make implicit function declarations fatal

- src/rc/openrc-run.c
This fixes the problem with the agetty scripts not being able to run. Without enough memory the string was being cut off.
> Fix memory size

- src/rc/checkpath.c
This avoids opening directories/files with read permission, which is
sometimes rejected by selinux policy.
Bug: https://bugs.gentoo.org/667122
> checkpath: use O_PATH when available

- src/rc/supervise-daemon.c
The following will cause a segfault due to NULL being
passed to `strcmp(3)`
```
$ RC_SVCNAME=foo supervise-daemon
```
Fix the bounds check on `argc` in `main`. If `argc<=1`, then
it is not safe to dereference `argv[1]`.
> src/rc/supervise-daemon.c: do not pass NULL to strcmp

- user-guide.md
I found the original note a little confusing, since using rc-update will
add it to a runlevel so it *is* auto-started when the system reaches
that runlevel again, but I don't think that was the intended meaning of
'auto-start', so hopefully this makes it a little more clear.
> user-guide: clarify note for Runlevels/rc-update usage

- man/start-stop-daemon.8
Until now there was a small typo in the description of `-m, --make-pidfile` regarding the background option:
```
-m, --make-pidfile
Saves the pid of the daemon in the file specified by the -p, --pidfile option. Only useful when used with daemons that run
in the foreground and forced into the background with the --b, --background option.
```
while in reality the abbreviation of `--background` is `-b` and not `--b`. This small PR fixes that :)
> start-stop-daemon: fix typo in manpage

- man/supervise-daemon.8
- src/rc/supervise-daemon.c
`supervise-daemon` was apparently overlooked when support for the `SSD_IONICELEVEL` environment variable was added. This commit brings `supervise-daemon` up to parity with `start-stop-daemon` with respect to this environment variable.
> supervise-daemon: implement SSD_IONICELEVEL

- sh/rc-mount.sh
Busybox timeout does not support the `-k` flag. As such, invoking fuser
from do_unmount never worked without this patch. This went unnoticed as
standard error is redirected to /dev/null. This patch fixes this by
simply removing the incompatible `-k` flag.
[Ariadne: the `-k` is redundant anyway, since we are sending the KILL
signal to begin with.]
> rc-mount: make timeout invocation compatible with busybox timeout

- src/rc/broadcast.c
Fix the following error:
broadcast.c:41:21: error: '__UT_LINESIZE' undeclared (first use in this function); did you mean 'UT_LINESIZE'?
#define UT_LINESIZE __UT_LINESIZE
^~~~~~~~~~
Constant UT_LINESIZE is defined in <utmp.h> provided by musl.
> Fix undeclared UT_LINESIZE on musl 1.2

- init.d/bootmisc.in
During boot if the "previous_dmesg" setting is enabled in
/etc/conf.d/bootmisc then during the 1st boot of a machine the
bootmisc init.d script will attempt to move a nonexistant dmesg
file, so generating an error on the console.
Modify the script to only move an existing file.
> init.d/bootmisc.in: prevent error due to nonexistant file

- init.d/devfs.in
Since I read this https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.17-Devtmpfs-Change I've been running Alpinelinux with /dev mounted noexec without issues.
> init.d/devfs: default mount /dev noexec

- man/start-stop-daemon.8
- man/supervise-daemon.8
- sh/start-stop-daemon.sh
- sh/supervise-daemon.sh
- src/rc/start-stop-daemon.c
- src/rc/supervise-daemon.c
Add the securebits of the capabilities feature and the No New Privs flag for Linux. This should increase the security of the running daemon, if the options are used.
This is how I tested it if it works:
I execute the following command as `root` with the securebit `SECBIT_NOROOT`:
```sh
RC_SVCNAME=test ./supervise-daemon test --start --capabilities ^cap_chown,^cap_net_bind_service --secbits 0x01 /usr/bin/sleep 60
```
And checked if the permitted set is the same as the inheritable set:
```sh
$ cat /proc/14757/status
[...]
CapInh:	0000000000000401
CapPrm:	0000000000000401
[...]
```
I execute the following command as `root` with the No New Privs flag:
```sh
RC_SVCNAME=test ./supervise-daemon test --start --no-new-privs /usr/bin/sleep 60
```
And checked if the No New Privs flag is set:
```sh
$ …
```
> Add securebits and No New Privs flags support for Linux

- service-script-guide.md
The comment block for `want` seemed to be unintentionally part of the `use` block. Added a newline so `want` will have its own section.
> Add newline for `want`

- meson.build
- sh/start-stop-daemon.sh
Fix indentation in the meson.build file.
Use consistent args passing in start-stop-daemon.
> Small format improvements

- sh/binfmt.sh.in
This Pull Request closes #492.
According to <https://freedesktop.org/software/systemd/man/binfmt.d.html#Configuration%20Format>:
> *Empty lines* and lines beginning with ";" and "#" are ignored.
> Note that this means you may not use those symbols as the delimiter in binary format rules.
> binfmt: ignore empty lines (#492)

- init.d/seedrng.in
The value of ${seed_dir} may have spaces in it, making the current
argument string building method unsafe. Instead, use positional
parameters to pass these arguments safely.
> seedrng: use posix positional params to avoid space splitting

- src/openrc/rc.c
The two lines seem to both belong to --override, but made into seperate
array elements accidentally, making options after --override and their
help mismatch. This fixes it.
> openrc: fix help messages

- init.d/hwclock.in
Starting with grep version 3.8, the hwclock init script logs warnings about stray backslashes:
> hwclock | * Setting system clock using the hardware clock [UTC] ... 
> hwclock |grep: warning: stray \ before -
> hwclock |grep: warning: stray \ before -
This is caused by the check for existence of the `--noadjfile` argument in function `get_noadjfile()`.
Replacing the affected logic with an explicit argument denoting the pattern as such resolves the issue.
Fixes #548
> Avoid warning on grep 3.8 in hwclock

- meson.build
- src/start-stop-daemon/start-stop-daemon.c
- src/supervise-daemon/supervise-daemon.c
On systems with a very large `RLIMIT_NOFILE`, calling `close()` in a loop from 3 to `getdtablesize()` effects an enormous number of system calls. There are better alternatives. Both BSD and Linux have the `closefrom()` system call that closes all file descriptors with indices not less than a specified minimum. Have `start-stop-daemon` call `closefrom()` on systems where it's implemented, falling back to the old loop elsewhere.
Likewise, calling `fcntl(i, F_SETFD, FD_CLOEXEC)` in a loop from 3 to `getdtablesize()` raises a similar performance concern. Linux 5.11 and onward has a `close_range()` system call with a `CLOSE_RANGE_CLOEXEC` flag that sets the `FD_CLOEXEC` flag on all file descriptors in a specified range. Have `supervise-daemon` utilize this feature on systems where it's …
> start-stop-daemon, supervise-daemon: use closefrom()/close_range()

- src/openrc/rc.c
malloc (called by xasprintf) is not async-signal-safe. beside, the string here is constant, so there's no need to malloc it all.
eerrorx isn't async-signal-safe either (due to calling fprintf and exit) but consequence of them are _typically_ not as grave as calling malloc while it's internal state is inconsistent.
Bug: https://github.com/OpenRC/openrc/issues/589
> openrc: avoid unnecessary malloc inside sig-handler

- src/swclock/swclock.c
this was reported by codeql's scan as a TOCTOU bug. while that's true in theory, i don't believe it would've had any practical effect.
a better justification for this change might be the fact that it upgrades from `utime` (which is depreciated by POSIX [0]) to `futimens`.
[0]: https://www.man7.org/linux/man-pages/man3/utime.3p.html#FUTURE_DIRECTIONS
> swclock: fix codeql warning and upgrade to futimens

- src/openrc/rc-logger.h
- src/shared/helpers.h
- src/shared/misc.h
- src/shared/plugin.h
- src/shared/schedules.h
clang-tidy evaluates the headers individually, apparently, when invoked
via meson's clang-tidy target, so let's make them standalone by
including what they need.
> openrc, shared: make headers standalone in prep. for clang-tidy

- src/seedrng/seedrng.c
`seed_dir` gets allocated via xstrdup but never gets freed - which clang-tidy flags as a memory leak.
instead of free-ing the allocation, just don't allocate to begin with since there's no need for it.
also bump the copyright year.
> seedrng: fix memory leak reported by clang-tidy

- src/seedrng/seedrng.c
this was mistakenly changed to 2023 instead of 2022-2023 in 63a5ee3d
> seedrng: fix copyright year

- meson.build
- src/libeinfo/einfo.h
- src/librc/librc-misc.c
- src/librc/librc.c
- src/openrc-shutdown/broadcast.c
- src/openrc-shutdown/openrc-shutdown.c
- src/openrc/rc.c
- src/shared/_usage.c
- src/shared/helpers.h
- src/start-stop-daemon/start-stop-daemon.c
- src/supervise-daemon/supervise-daemon.c
Rename attribute macros to namespaced RC_*
This conflicts with linux-headers which uses __unused for some padding members
on ppc64le at least.
Closes: https://github.com/OpenRC/openrc/issues/622
> Drop use of custom _unused

- src/libeinfo/einfo.h
Make function declarations use the EINFO_RESTRICT macro instead of __EINFO_RESTRICT which gets treated as the name of the argument.
> einfo.h: fix EINFO_RESTRICT macro usage

- src/fstabinfo/fstabinfo.c
problem:
* vfork has been removed from POSIX [0].
* clang-tidy flags the `strerror` and `eerror` call inside the vfork-ed
child as undefined behavior.
solution: use posix_spawnp, which is serves similar purpose and is
specified in posix. and as an added bonus, it's also easier to use and
less lines of code.
[0]: https://www.man7.org/linux/man-pages/man2/vfork.2.html#CONFORMING_TO
> fstabinfo: remove vfork and deal with EINTR

- src/openrc/rc.c
`free` is not async-signal-safe and calling it inside a signal handler
can have bad effects, as reported in the musl ML:
https://www.openwall.com/lists/musl/2023/01/23/1
the solution:
- keep track of weather remove_pid() is being called from inside a
signal handler or not.
- if it's inside a signal handler then DO NOT call free - instead put
that pointer into a "to be freed later" list.
- if it's not inside a signal handler then take the "to be freed later"
list and free anything in it.
the pid list will be accessed inside the SIGCHLD signal handler. so we
must ensure SIGCHLD handler doesn't get invoked while the list is at an
inconsistent state making it unsafe to interact with.
according to the linux manpage, the "safe" variant may not be available
on all platform. however we bundle our …
> rc: signal safety improvement

- src/openrc-run/openrc-run.c
- src/shared/misc.c
- src/shared/misc.h
```
restarting a service with --no-deps ran into a "hairy workaround", which
had a few problems discussed in [1]:
- it ignores --dry-run, really restarting the requested service
- if the service was stopped, the program is started but the service
status stays stopped. This makes long-lived services impossible to
(re)start again (pid already exists and running), and the service also
won't stop on shutdown.
The kludge had a long comment describing the following situation:
- openvpn needs net and dns
- net restarts dns
- dns needs net
If the restart in net handled deps, openrc would deadlock waiting for
net in dns' restart, as net won't be started until that is done.
Restarting with --nodeps works around the deadlock, but can display
errors without the kludge (note that the services did …
```
> openrc-run: remove kludge in restart --no-deps

- src/librc/librc-misc.c
This was originally introduced in 14625346c07a2a66fe77ce578c9423918bec1d97 with an example list (just one for rc_parallel) of options. Let's add in rc_interactive as it's a pretty obvious thing one might want to override.
See https://forums.gentoo.org/viewtopic-p-8694588.html.
> librc: allow overriding rc_interactive on kernel command line

- src/einfo/einfo.c
Fix typo preventing the args for the vewend applet from being handled.
> einfo: fix vewend applet args

- man/start-stop-daemon.8
This commit removes the secondary mention of the -2/--stderr flag in the start-stop-daemon man page. The flag's functionality was already sufficiently described in an earlier section of the text.
> man: Remove Duplicate Description of -2/--stderr Flag

- bash-completion/rc-service
It breaks bash-completion.
It's not necessary to set extglob as patterns in '[[' after '==' are always matched as if extglob were set.
Closes: #636
> bash-completion/rc-service: don't set or unset extglob

- src/openrc/rc.c
Commit fc4f15d6cd8e7884f7094e5d3749b01f2d5a448f broke the automatic restart of services having runlevel-specific conf.d files.
The double dirname() is not a mistake, but the way of getting from the service script in init.d to the upper directory containing the conf.d directory. dirname() modifies the argument in-place, so the second call operated on a modified value. To make it more obvious what is going on, have the second call operate on the returned value from the first call.
Fixes: fc4f15d ("openrc: fix double-assignment to dir")
> rc: fix automatic restart with runlevel-specific conf.d files

- meson.build
- src/libeinfo/libeinfo.c
- src/shared/helpers.h
`>=glibc-2.38` implements strlcpy, strlcat, etc so check for those functions
with Meson and don't provide conflicting prototypes.
Fixes: https://github.com/OpenRC/openrc/issues/643
> Don't re-define strlcpy/strlcat with >=glibc-2.38

- meson.build
- src/shared/misc.c
- src/shared/misc.h
- src/start-stop-daemon/start-stop-daemon.c
- src/supervise-daemon/supervise-daemon.c
Make sure that we use close_range also with musl libc, using syscall directly.
This fixes a severe performance issue when running openrc under docker where the maxfd may be 1G.
> start-stop-daemon, supervise-daemon: use close_range with musl

- tools/meson_final.sh
When building on embedded SDKs such as Buildroot or Yocto, if OpenRC has a previous installation, the package will fail the installation step as the openrc-init is already a symlink to "${DESTDIR}/${sbindir}"/init. Force symlinking to prevent errors when reinstalling the package.
> Force symlinking of openrc-init to init

- man/start-stop-daemon.8
> update start-stop-daemon manual to include --quiet

- sh/rc-cgroup.sh
Some services, like docker, creates and manages /sys/fs/cgroup/<service> themselves. Avoid conflict with the openrc created cgroup path by adding a `openrc.` prefix.
Fixes: https://github.com/OpenRC/openrc/issues/680
> sh/rc-cgroup.sh: add openrc. prefix the cgroupv2 path

- man/einfo.3
- meson.build
- meson_options.txt
- src/libeinfo/libeinfo.c
- src/libeinfo/meson.build
Remove the curses code and make the HAVE_TERMCAP-gated "fallbacks" always present. This makes an ANSI terminal required for colors.
X-Gentoo-Bug: https://bugs.gentoo.org/904277
Closes: https://github.com/OpenRC/openrc/issues/619
> Drop curses

- src/libeinfo/libeinfo.c
xterm-kitty is a wayland color capable terminal, so add it.
> Add xterm-kitty to color capable term list

- src/librc/librc.c
Use heap allocations instead. This avoids warnings:
```
../src/librc/librc.c: In function ‘rc_service_mark’:
../src/librc/librc.c:817:58: warning: ‘/’ directive output may be truncated writing 1 byte into a region of size between 0 and 4095 [-Wformat-truncation=]
817 |                         snprintf(was, sizeof(was), "%s/%s/%s",
|                                                          ^
../src/librc/librc.c:817:25: note: ‘snprintf’ output 3 or more bytes (assuming 4098) into a destination of size 4096
817 |                         snprintf(was, sizeof(was), "%s/%s/%s",
|                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
818 |                             file, dir->value, base);
|                             ~~~~~~~~~~~~~~~~~~~~~~~
../src/librc/librc.c:822:58: warning: …
```
> librc: avoid using fixed-size buffers for paths

- src/openrc-shutdown/broadcast.c
Get rid of the alarm/setjmp/longjmp.
Trust that the kernel will not block with O_NDELAY.
Use write() instead of stdio.
Bug: https://bugs.gentoo.org/923326
> openrc-shutdown: simplify broadcast function

- src/start-stop-daemon/start-stop-daemon.c
The stop schedule code calls syslog, so we need to open a syslog connection so the process name will get properly logged on musl, and we can ensure the pid gets logged and the right facility is used.
> start-stop-daemon: open syslog

- src/librc/librc-depend.c
some changes for code redability, and fixing leaking the whole internals of the deptree at the end of rc_deptree_update.
> librc/librc-depend.c: small refactor

- src/openrc-init/openrc-init.c
Avoids compiler warning about discarded const.
> openrc-init: replace putenv with setenv

- src/start-stop-daemon/meson.build
- src/start-stop-daemon/start-stop-daemon.c
musl sched_setscheduler() is only a stub in musl and the glibc implementation does "the wrong thing". Use pthread_setschedparam instead.
ref: https://www.openwall.com/lists/musl/2016/03/01/5
fixes: https://github.com/OpenRC/openrc/issues/689
> start-stop-daemon: fix setting scheduler with musl

- init.d/root.in
containers on linux might require filesystems to be mounted with
different propagation than the kernel default of 'private':
by setting 'shared' in fstab for / options, one can now make the
fs hierarchy shared.
Note we use 'rshared' to make other existing mounts shared as well
because the setting is contagious and it seemed more logical to
behave as if the setting was set on / immediately (and thus inherited
by other mounts)
This fixes #525.
> init.d/root: add support for 'shared' fstab option on /

- meson.build
- meson_options.txt
- src/start-stop-daemon/meson.build
- src/start-stop-daemon/start-stop-daemon.c
- src/supervise-daemon/meson.build
- src/supervise-daemon/supervise-daemon.c
For linux systems, libcap is a lightweight dependency. Also, making it optional requires that service scripts be written to deal with the possibility that capabilities are not supported.
This fixes #739.
X-Gemtoo-Bug: https://bugs.gentoo.org/939543
> make libcap a hard requirement

- src/librc/librc-misc.c
Bug: https://bugs.gentoo.org/939758
Fixes: 0702a064a93af9a98e6954e035867882778f4268
> librc: fix getline return value check

- man/openrc-run.8
- src/shared/misc.c
This was only used in gentoo prefix installations which we no longer support.
> remove RC_PREFIX environment variable

- sh/openrc-run.sh.in
- user-guide.md
This adds support for multiple limits in rc_ulimit as identified in  https://github.com/OpenRC/openrc/issues/399#issuecomment-810461921
The inconsistent aspects of the ulimit shell builtin ([#399](https://github.com/OpenRC/openrc/issues/399)) still remain, but it works well until setrlimit is implemented.
I have also updated the incorrect documentation in #701: niceness is not settable here, only RLIMIT_NICE, and only when using bash's ulimit.
Mark
> rc_ulimit: support multiple limits

- service-script-guide.md
- sh/openrc-run.sh.in
- src/librc/librc-depend.c
- src/librc/librc-misc.c
- src/librc/librc.c
- src/librc/meson.build
- src/librc/rc.h.in
- src/mark_service/mark_service.c
- src/openrc-run/openrc-run.c
- src/openrc/rc.c
- src/service/service.c
- src/shared/_usage.h
- src/shared/misc.c
- src/start-stop-daemon/start-stop-daemon.c
- src/supervise-daemon/supervise-daemon.c
- src/value/value.c
- user-guide.md
> User Services 2.0

- user-guide.md
I noticed some typos/grammar issues while reading the docs, here's a fix :)
> docs: fix typos/grammar in user-guide.md

- src/shared/misc.c
The syscall expects unsigned integers.  Notably, if this wrapper is called, `UINT_MAX` is passed as `last`, and conversion from unsigned to signed is implementation-defined.
> shared/misc: fix types on close_range wrapper

- sh/openrc-run.sh.in
Without this patch, OpenRC loads user configuration files for system-supplied services from `~/.config/rc/$SERVICE` instead of `~/.config/rc/conf.d/$SERVICE`. Since the latter is [documented in the user-guide](https://github.com/OpenRC/openrc/blob/0.60.1/user-guide.md#user-services----experimental), and used for user services not supplied by the system, I believe it to be the correct location.
Note that the `_usr_conf_d` variable is probably a bit inappropriately named as the similarly named `_conf_d` points to the system conf.d directory while `_usr_conf_d` points to the base rc configuration directory. Might be worthwhile to rename it…
This is a fixup for ae9d743207f27481efe2c80593eea51cd8742ab2.
> openrc-run: Fix loading of user configs for system-supplied user services

- man/openrc-run.8
- man/start-stop-daemon.8
- man/supervise-daemon.8
- sh/start-stop-daemon.sh
- sh/supervise-daemon.sh
- src/start-stop-daemon/start-stop-daemon.c
- src/supervise-daemon/supervise-daemon.c
OpenRC already supports redirecting standard output/error of services. This patch adds support for redirecting standard input as well. I encountered the lack of this feature while working on a user service for a Wayland compositor status bar which reads status text to be displayed from stdin. Input redirection allows me to connect this user services with another user service providing the status text via a named pipe.
Note that input redirection is also supported by systemd (and potentially other service supervisors) through the `StandardInput=` directive [\[1\]][1]. I intentionally did not implement redirection from a program as an input as I believe that in such a case the input program (assuming it is long-running) should be supervised by OpenRC as well and the two should be connected …
> openrc-run: Support standard input redirection too

- src/openrc-init/openrc-init.c
rather than waiting 3 seconds always, check if there's any
reapable children left or not. if there are none left, we can
shutdown early.
Fixes: https://github.com/OpenRC/openrc/issues/797
> openrc-init: faster shutdown 

- init.d/consolefont.in
- init.d/save-termencoding.in
- init.d/savecache.in
- init.d/termencoding.in
- sh/init-early.sh.Linux.in
- sh/init.sh.Linux.in
- sh/openrc-user.sh.in
- src/openrc/rc.c
- src/shared/misc.c
Instead, move caches to /var/cache/openrc. If /var is not mounted, cache will not be used and the deptree would be regenerated.
> openrc: Don't use libexec for data cache.

- src/shared/misc.c
snprintf return value does not include the nul-byte, so return of `== size` is also a truncation case.
> misc: fix off by one

- init.d/user.in
- sh/openrc-user.sh.in
- src/openrc/rc.c
the boot runlevel systemwide has the special semantics of being automatically added to all other runlevels, while at the same time not having as much special interactions as the sysinit runlevel, so let's use it here to allow users to reliably set services to start *before* login completes, while the 'default' runlevel does proper parallelization with the login shell.
this increases the reliability of sessions, and avoids races such as `dbus-launch-if-needed` running before `init.d/dbus` has properly started, as well as allowing `rc-service --user ... status` to be ran in profile scripts to check for services in order to export vars.
> openrc-user: create by default and wait for boot runlevel at login

- init.d/cgroups.in
Just a cosmetic change with no real changes, more than the visual impact when running mount
> cgroups: set (irrelenvant) device string to cgroup2

- src/start-stop-daemon/start-stop-daemon.c
- src/supervise-daemon/supervise-daemon.c
there's no real reason to leak those into the environment.
Closes: https://github.com/OpenRC/openrc/issues/808
> *-daemon: filter all RC_ and SSD_ variables for the service

- meson.build
These flags are set by the WARNING_LEVEL=3 setting in the project options.
> build: remove redundant warning flags

- src/librc/librc-daemon.c
- src/librc/librc-depend.c
- src/librc/librc-misc.c
- src/librc/librc.c
- src/librc/librc.h
- src/librc/rc.h.in
- src/openrc-run/openrc-run.c
- src/openrc/rc.c
- src/pam_openrc/pam_openrc.c
- src/shared/helpers.h
- src/shared/misc.c
- src/shared/misc.h
gives us atomic operations, removes almost all path string allocations, and reduces the number of syscalls
> librc: use dirfd and *at functions.

- init.d/sysfs.in
eg. cilium expects /sys/fs/bpf to be mounted. systemd mounts it here as well.
> sysfs: mount /sys/fs/bpf if available

- src/openrc-run/meson.build
- src/openrc-run/openrc-run.c
- src/shared/misc.c
- src/shared/misc.h
* misc: fix the exclusive lockfile fd remaining open in the caller of `exec_service`
* openrc-run: properly wait for the exclusive flock in svc_wait and svc_exec
* openrc: don't solve start dependencies, instead have services start their own dependencies, it simplifies the overall mechanism, aligns the code path of `openrc` with the codepath of `rc-service`, and i think that allows for better parallelism (not sure, need to test some more)
> wait for exclusive fds properly

- src/openrc-run/openrc-run.c
- src/shared/misc.c
- src/shared/misc.h
openrc-run can be called from places that don't reset the signal mask
before exec, example being the pam close_session session hook called
from runuser, which leads to svc_exec hanging, as SIGCHLD is never
delivered.
Bug: https://bugs.gentoo.org/953748
> unblock signal handlers during signal_setup

- init.d/meson.build
it's the standard for symlinks to exist as relative pointers.
Fixes: https://github.com/OpenRC/openrc/issues/847
> init.d/meson.build: install agetty as a relative symlink

- src/librc/librc.c
Without this patch, this code therefore closes FD 0 repeatedly.
See https://github.com/OpenRC/openrc/pull/851
This fixes a regression from 27eae2c380239e7baf113c1b228c6fe679e6a541.
> librc: dirfd is initalized with zero not with -1

- man/rc-update.8
The Ar macro is used for arguments. The Ic macro is used for internal commands. The latter is suitable for subcommands of rc-update.
When rendered via man, this makes commands and variable arguments visually distinct (bold and underlined respectively by default).
> man: use Ic macro for rc-update commands

- init.d/meson.build
- runlevels/meson.build
The getty symlinks are installed both in the init.d directory and the default runlevel directory. This makes the getty installation consistent with the rest of the runlevel setup.
> build: fix installation of getty symlinks

- src/start-stop-daemon/start-stop-daemon.c
Without this, the help output from `--notify` onwards is incorrectly off-by-one, e.g.:
```
--notify <arg>                Display this help output
-h, --help                        Disable color output
-C, --nocolor                     Display software version
```
By aligning its length with that of `longopts`, this also fixes a segfault we've observed in our arm64 builds.
> start-stop-daemon: add longopts_help value for --notify

- AUTHORS
- init.d/s6-svscan.in
- s6-guide.md
- sh/gendepends.sh.in
- sh/meson.build
- sh/s6-svscanboot.sh.in
- sh/s6.sh
This commit modernizes the support for the supervisor=s6
backend. It reworks how the supervision tree is started and how the services are defined.
The s6-svscan service now runs its own catch-all logger,
logging to $RC_SVCDIR/s6-logs.
A service defining supervisor=s6 now has an automatic "need"
dependency to s6-svscan. A service directory will be automatically built from the information in the service file, under the $RC_SVCDIR/s6-services repository. These service directories are cached until the service file (or config) changes. So, services don't need to provide their service directories themselves anymore; they still can, but they'll need to do the s6-sv[un]link thing themselves.
The documentation has been updated.
Anna, please add yourself to the AUTHORS file, because it is …
> supervisor=s6: rework support

- man/einfo.3
- sh/functions.sh.in
- src/libeinfo/libeinfo.c
This fixes issues #868 and #869, plus a trivial fix for the `einfo` man page.
> Fixes for eindent: out-of-bounds array access, proper alignment

- src/start-stop-daemon/start-stop-daemon.c
- src/supervise-daemon/supervise-daemon.c
in the current order, we use pam_start and read /etc/group *after* chroot-ing. this is undocumented in the manpages, causes issues (#543) and is also very inconsistent (e.g we get the gid from the root database, not the chroot one. also stuff like expand_home() happens before chroot etc).
so make pam_start and getgrouplist happen before chroot().
Ref: https://github.com/OpenRC/openrc/pull/517
Fixes: https://github.com/OpenRC/openrc/issues/543
> *-daemon: fix order of chroot

- src/supervise-daemon/supervise-daemon.c
This diff fixes incorrect output of --help due to missing help string. Because longots_help arrays was shorter by one element, running --help produced incorrect result. It could also lead to crash due to OOB access.
Before:
$ RC_SVCNAME=foo supervise-daemon foo --help | tail -n 9
--stderr-logger <arg>         Redirect stderr to process
-3, --reexec                      reexec (used internally)
--notify <arg>                Display this help output
-h, --help                        Disable color output
-C, --nocolor                     Display software version
-V, --version                     Run verbosely
-v, --verbose                     Run quietly (repeat to suppress errors)
-q, --quiet                       Run in user mode
-U, --user                        healthcheck-timer
After: …
> Add missing description for --notify option of supervise-daemon

- sh/binfmt.sh.in
This is consistent with systemd, and kind of expected.
> binfmt: also look in /usr/local/lib/binfmt.d

- src/shared/schedules.c
Make it consistent with the other one: in case of error report failed input.
> Fix error message in parse_schedule

- src/librc/librc-depend.c
- src/librc/librc.c
this is a temporary fix, in a system that boots with / as rw, /run unmounted, and has rc_parallel on, openrc would create a dirfd to /run/openrc before mounting /run, thus keeping an open fd to the old /run mountpoint, and creating 'exclusive' lockfiles under it, that subsequent services can't see nor lock on.
Fixes: https://github.com/OpenRC/openrc/issues/859
Fixes: 07d6f4d5
> librc: don't create /run/openrc itself on demand.

- src/shared/misc.c
otherwise /run/openrc might not exist, and result on svcdirfd being -1
Fixes: https://github.com/OpenRC/openrc/issues/888
> shared/misc: open svcdir dirfd after update_needed

- src/librc/librc-depend.c
init.sh creates the directory, which means we never actually do it here early at boot
Fixes: 9c3f974
Fixes: https://github.com/OpenRC/openrc/pull/893
> librc-depend: clear dirfds unconditionally

- src/openrc-run/openrc-run.c
4d8a5c4 added the timeout logic from svc_wait into svc_exec, with the goal of avoiding stalling the boot process should a service hang, however we failed to mention the change in NEWS, and some critical services like postgres rely on inifinite timeout for `stop()`.
this logic was also sharing the `timeout` keyword from `depend()`, which is not very clean
let's revert the timeout logic, and properly re-introduce it later, with effort put into making sure no issues happen.
Bug: https://github.com/OpenRC/openrc/issues/896
> openrc-run: remove timeout from start/stop

- src/libeinfo/libeinfo.c
nothing fancy, just teaching `libeinfo` that `TERM=alacritty` means we can show colours
> recognise alacritty as a color terminal

- NEWS.md
- user-guide.md
We don't consider these experimental anymore as of 0.62 as bugs have been ironed out, they've been in Gentoo ~arch for several months, and in an Alpine release for several months also.
> NEWS.md, user-guide.md: no longer experimental

- etc/rc.conf
- src/pam_openrc/pam_openrc.c
we should also mark the service as stopped instead of failed -- at least while we're still in this experimental step
> silence out pam_openrc on login, and add rc_autostart_users to rc.conf

- init.d/sysfs.in
for rationale, see
https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9ba817fb7c6afd3c86a6d4c3b822924b87ef0348
> sysfs: mount tracefs explicitly if available

- src/librc/librc.h
- src/mountinfo/mountinfo.c
Fixes #902 
This builds on NetBSD 10.1 after adding some preprocessor directives. Have not tested these changes on other systems or OSes.
> Builds on NetBSD 10.1 now

- src/librc/librc.c
Fixes: https://bugs.gentoo.org/963052
> librc: remove d->d_name, not pathname, in rm_dir loop
